/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\18th_century_city_building_low_poly.glb
Author: Zaheer Ul Islam (https://sketchfab.com/ZaheerUlIslam)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/18th-century-city-building-low-poly-3a2bdf0032424f78bbfdcc003624b95d
Title: 18th Century City Building Low Poly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/18th_century_city_building_low_poly.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 657.44, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[536.36, 1602.95, 658.38]}>
          <mesh geometry={nodes.Building_Texture_0.geometry} material={materials.Texture} />
          <mesh geometry={nodes.Building_Base001_0.geometry} material={materials['Base.001']} />
          <mesh geometry={nodes.Building_Roof_0.geometry} material={materials.Roof} />
          <mesh geometry={nodes.Building_ButimenRoofing_0.geometry} material={materials.ButimenRoofing} />
        </group>
        <group position={[16.67, -97.34, 2.57]} rotation={[-Math.PI / 2, 0, 0]} scale={[1086.93, 2120.84, 100]}>
          <mesh geometry={nodes.Road_Sidewalk_0.geometry} material={materials.Sidewalk} />
          <mesh geometry={nodes.Road_Line_0.geometry} material={materials.Line} />
          <mesh geometry={nodes.Road_Road_0.geometry} material={materials.Road} />
          <mesh geometry={nodes.Road_Crossing_0.geometry} material={materials.Crossing} />
        </group>
        <group position={[1007.04, 339.63, 1234.55]} rotation={[-Math.PI / 2, 0, 0]} scale={[5.91, 5.91, 297.02]}>
          <mesh geometry={nodes.StreetLight_StreetLight_0.geometry} material={materials.StreetLight} />
          <mesh geometry={nodes.StreetLight_Bulb_0.geometry} material={materials.Bulb} />
        </group>
        <group position={[1007.04, 339.63, -47.84]} rotation={[-Math.PI / 2, 0, 0]} scale={[5.91, 5.91, 297.02]}>
          <mesh geometry={nodes.StreetLight001_StreetLight001_0.geometry} material={materials['StreetLight.001']} />
          <mesh geometry={nodes.StreetLight001_Bulb001_0.geometry} material={materials['Bulb.001']} />
        </group>
        <group position={[1007.04, 339.63, -1514.31]} rotation={[-Math.PI / 2, 0, 0]} scale={[5.91, 5.91, 297.02]}>
          <mesh geometry={nodes.StreetLight002_StreetLight002_0.geometry} material={materials['StreetLight.002']} />
          <mesh geometry={nodes.StreetLight002_Bulb002_0.geometry} material={materials['Bulb.002']} />
        </group>
        <group position={[1007.04, 339.63, -2047.53]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[5.91, 5.91, 297.02]}>
          <mesh geometry={nodes.StreetLight003_StreetLight003_0.geometry} material={materials['StreetLight.003']} />
          <mesh geometry={nodes.StreetLight003_Bulb003_0.geometry} material={materials['Bulb.003']} />
        </group>
        <group position={[1008.56, 321.78, -2096.54]} rotation={[-Math.PI / 2, 0, 0]} scale={[23.9, 10.79, 50.58]}>
          <mesh geometry={nodes.Cube_Signal_0.geometry} material={materials.Signal} />
          <mesh geometry={nodes.Cube_White_0.geometry} material={materials.White} />
          <mesh geometry={nodes.Cube_Red_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Cube_Yellow_0.geometry} material={materials.Yellow} />
          <mesh geometry={nodes.Cube_Green_0.geometry} material={materials.Green} />
        </group>
        <group position={[1008.56, 321.78, -2002.03]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[23.9, 10.79, 50.58]}>
          <mesh geometry={nodes.Cube001_Signal_0.geometry} material={materials.Signal} />
          <mesh geometry={nodes.Cube001_White_0.geometry} material={materials.White} />
          <mesh geometry={nodes.Cube001_Red_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Cube001_Yellow_0.geometry} material={materials.Yellow} />
          <mesh geometry={nodes.Cube001_Green_0.geometry} material={materials.Green} />
        </group>
        <group position={[1696.43, 412.46, -2002.03]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[23.9, 10.79, 50.58]}>
          <mesh geometry={nodes.Cube004_Signal002_0.geometry} material={materials['Signal.002']} />
          <mesh geometry={nodes.Cube004_White002_0.geometry} material={materials['White.002']} />
          <mesh geometry={nodes.Cube004_Red002_0.geometry} material={materials['Red.002']} />
          <mesh geometry={nodes.Cube004_Yellow002_0.geometry} material={materials['Yellow.002']} />
          <mesh geometry={nodes.Cube004_Green002_0.geometry} material={materials['Green.002']} />
        </group>
        <group position={[1696.43, 412.46, -2096.54]} rotation={[-Math.PI / 2, 0, 0]} scale={[23.9, 10.79, 50.58]}>
          <mesh geometry={nodes.Cube005_Signal002_0.geometry} material={materials['Signal.002']} />
          <mesh geometry={nodes.Cube005_White002_0.geometry} material={materials['White.002']} />
          <mesh geometry={nodes.Cube005_Red002_0.geometry} material={materials['Red.002']} />
          <mesh geometry={nodes.Cube005_Yellow002_0.geometry} material={materials['Yellow.002']} />
          <mesh geometry={nodes.Cube005_Green002_0.geometry} material={materials['Green.002']} />
        </group>
        <group position={[1009.28, 425.18, -2040.3]} rotation={[-Math.PI / 2, 0, 0]} scale={[35.32, 1.12, 40.62]}>
          <mesh geometry={nodes.Cube006_Base007_0.geometry} material={materials['Base.007']} />
          <mesh geometry={nodes.Cube006_Sign_0.geometry} material={materials.Sign} />
        </group>
        <group position={[1009.28, 425.18, -2054.84]} rotation={[-Math.PI / 2, 0, 0]} scale={[35.32, 1.12, 40.62]}>
          <mesh geometry={nodes.Cube007_Base002_0.geometry} material={materials['Base.002']} />
          <mesh geometry={nodes.Cube007_Sign001_0.geometry} material={materials['Sign.001']} />
        </group>
        <group position={[1130.38, 455.85, -2043.4]} rotation={[-Math.PI / 2, 0.79, 0]} scale={[24.79, 0.78, 22.15]}>
          <mesh geometry={nodes.Cube008_Base004_0.geometry} material={materials['Base.004']} />
          <mesh geometry={nodes.Cube008_Sign003_0.geometry} material={materials['Sign.003']} />
        </group>
        <group position={[1016.55, 509.15, -2047.54]} rotation={[-Math.PI / 2, 0, -1.57]} scale={[35.32, 1.12, 40.62]}>
          <mesh geometry={nodes.Cube009_Base005_0.geometry} material={materials['Base.005']} />
          <mesh geometry={nodes.Cube009_Sign004_0.geometry} material={materials['Sign.004']} />
        </group>
        <group position={[1002.01, 509.15, -2047.6]} rotation={[-Math.PI / 2, 0, -1.57]} scale={[35.32, 1.12, 40.62]}>
          <mesh geometry={nodes.Cube010_Base006_0.geometry} material={materials['Base.006']} />
          <mesh geometry={nodes.Cube010_Sign005_0.geometry} material={materials['Sign.005']} />
        </group>
        <group position={[1005.48, 213.55, -1849.01]} rotation={[-Math.PI / 2, 0, 0]} scale={34.62}>
          <mesh geometry={nodes.Cube011_Base_0.geometry} material={materials.Base} />
          <mesh geometry={nodes.Cube011_StopSign_0.geometry} material={materials.StopSign} />
        </group>
        <group position={[1007.82, 339.63, 2012.36]} rotation={[-Math.PI / 2, 0, 0]} scale={[5.91, 5.91, 297.02]}>
          <mesh geometry={nodes.StreetLight004_StreetLight004_0.geometry} material={materials['StreetLight.004']} />
          <mesh geometry={nodes.StreetLight004_Bulb004_0.geometry} material={materials['Bulb.004']} />
        </group>
        <group position={[809.31, 213.55, 2010.14]} rotation={[-Math.PI / 2, 0, -1.57]} scale={34.62}>
          <mesh geometry={nodes.Cube012_Base008_0.geometry} material={materials['Base.008']} />
          <mesh geometry={nodes.Cube012_StopSign001_0.geometry} material={materials['StopSign.001']} />
        </group>
        <group position={[1007.91, 509.15, 2007.34]} rotation={[-Math.PI / 2, 0, 3.13]} scale={[35.32, 1.12, 40.62]}>
          <mesh geometry={nodes.Cube013_Base009_0.geometry} material={materials['Base.009']} />
          <mesh geometry={nodes.Cube013_Sign006_0.geometry} material={materials['Sign.006']} />
        </group>
        <group position={[1007.81, 509.15, 2021.87]} rotation={[-Math.PI / 2, 0, 3.13]} scale={[35.32, 1.12, 40.62]}>
          <mesh geometry={nodes.Cube014_Base010_0.geometry} material={materials['Base.010']} />
          <mesh geometry={nodes.Cube014_Sign007_0.geometry} material={materials['Sign.007']} />
        </group>
        <group position={[1003.28, 455.85, 2135.69]} rotation={[-0.79, 0, -1.57]} scale={[24.79, 0.78, 22.15]}>
          <mesh geometry={nodes.Cube015_Base011_0.geometry} material={materials['Base.011']} />
          <mesh geometry={nodes.Cube015_Sign008_0.geometry} material={materials['Sign.008']} />
        </group>
        <group position={[1015.13, 425.18, 2014.63]} rotation={[-Math.PI / 2, 0, -1.57]} scale={[35.32, 1.12, 40.62]}>
          <mesh geometry={nodes.Cube016_Base012_0.geometry} material={materials['Base.012']} />
          <mesh geometry={nodes.Cube016_Sign009_0.geometry} material={materials['Sign.009']} />
        </group>
        <group position={[1000.59, 425.18, 2014.58]} rotation={[-Math.PI / 2, 0, -1.57]} scale={[35.32, 1.12, 40.62]}>
          <mesh geometry={nodes.Cube017_Base013_0.geometry} material={materials['Base.013']} />
          <mesh geometry={nodes.Cube017_Sign010_0.geometry} material={materials['Sign.010']} />
        </group>
        <group position={[1054.53, 412.46, 2701.92]} rotation={[-Math.PI / 2, 0, -1.57]} scale={[23.9, 10.79, 50.58]}>
          <mesh geometry={nodes.Cube018_Signal003_0.geometry} material={materials['Signal.003']} />
          <mesh geometry={nodes.Cube018_White003_0.geometry} material={materials['White.003']} />
          <mesh geometry={nodes.Cube018_Red003_0.geometry} material={materials['Red.003']} />
          <mesh geometry={nodes.Cube018_Yellow003_0.geometry} material={materials['Yellow.003']} />
          <mesh geometry={nodes.Cube018_Green003_0.geometry} material={materials['Green.003']} />
        </group>
        <group position={[960.02, 412.46, 2701.6]} rotation={[-Math.PI / 2, 0, 3.14]} scale={[23.9, 10.79, 50.58]}>
          <mesh geometry={nodes.Cube019_Signal003_0.geometry} material={materials['Signal.003']} />
          <mesh geometry={nodes.Cube019_White003_0.geometry} material={materials['White.003']} />
          <mesh geometry={nodes.Cube019_Red003_0.geometry} material={materials['Red.003']} />
          <mesh geometry={nodes.Cube019_Yellow003_0.geometry} material={materials['Yellow.003']} />
          <mesh geometry={nodes.Cube019_Green003_0.geometry} material={materials['Green.003']} />
        </group>
        <group position={[962.32, 321.78, 2013.73]} rotation={[-Math.PI / 2, 0, 3.14]} scale={[23.9, 10.79, 50.58]}>
          <mesh geometry={nodes.Cube022_Signal004_0.geometry} material={materials['Signal.004']} />
          <mesh geometry={nodes.Cube022_White004_0.geometry} material={materials['White.004']} />
          <mesh geometry={nodes.Cube022_Red004_0.geometry} material={materials['Red.004']} />
          <mesh geometry={nodes.Cube022_Yellow004_0.geometry} material={materials['Yellow.004']} />
          <mesh geometry={nodes.Cube022_Green004_0.geometry} material={materials['Green.004']} />
        </group>
        <group position={[1056.83, 321.78, 2014.04]} rotation={[-Math.PI / 2, 0, -1.57]} scale={[23.9, 10.79, 50.58]}>
          <mesh geometry={nodes.Cube023_Signal004_0.geometry} material={materials['Signal.004']} />
          <mesh geometry={nodes.Cube023_White004_0.geometry} material={materials['White.004']} />
          <mesh geometry={nodes.Cube023_Red004_0.geometry} material={materials['Red.004']} />
          <mesh geometry={nodes.Cube023_Yellow004_0.geometry} material={materials['Yellow.004']} />
          <mesh geometry={nodes.Cube023_Green004_0.geometry} material={materials['Green.004']} />
        </group>
        <group position={[961.53, 65.04, -1269.96]} rotation={[-Math.PI / 2, 0, 0]} scale={[28.38, 41.35, 64.57]}>
          <mesh geometry={nodes.Cube024_Trash_0.geometry} material={materials.Trash} />
          <mesh geometry={nodes.Cube024_Gray_0.geometry} material={materials.Gray} />
        </group>
        <group position={[569.76, 65.04, 2010.93]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[28.38, 41.35, 64.57]}>
          <mesh geometry={nodes.Cube025_Trash001_0.geometry} material={materials['Trash.001']} />
          <mesh geometry={nodes.Cube025_Gray001_0.geometry} material={materials['Gray.001']} />
        </group>
        <group position={[288.35, 339.63, 2013.73]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[5.91, 5.91, 297.02]}>
          <mesh geometry={nodes.StreetLight005_StreetLight005_0.geometry} material={materials['StreetLight.005']} />
          <mesh geometry={nodes.StreetLight005_Bulb005_0.geometry} material={materials['Bulb.005']} />
        </group>
        <group position={[-537.08, 339.63, 2013.73]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[5.91, 5.91, 297.02]}>
          <mesh geometry={nodes.StreetLight006_StreetLight006_0.geometry} material={materials['StreetLight.006']} />
          <mesh geometry={nodes.StreetLight006_Bulb006_0.geometry} material={materials.material_0} />
        </group>
        <group position={[-537.08, 339.63, -1988.88]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[5.91, 5.91, 297.02]}>
          <mesh geometry={nodes.StreetLight007_StreetLight007_0.geometry} material={materials['StreetLight.007']} />
          <mesh geometry={nodes.StreetLight007_Bulb007_0.geometry} material={materials['Bulb.007']} />
        </group>
        <group position={[302.58, 339.63, -1988.88]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[5.91, 5.91, 297.02]}>
          <mesh geometry={nodes.StreetLight008_StreetLight008_0.geometry} material={materials['StreetLight.008']} />
          <mesh geometry={nodes.StreetLight008_Bulb008_0.geometry} material={materials['Bulb.008']} />
        </group>
        <group position={[916.72, 83.37, -568.48]} rotation={[-Math.PI / 2, 1.55, 0]} scale={[8.35, 123.67, 2.04]}>
          <mesh geometry={nodes.Cube029_Wood003_0.geometry} material={materials['Wood.003']} />
          <mesh geometry={nodes.Cube029_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <group position={[916.72, 83.37, 701.98]} rotation={[-Math.PI / 2, 1.55, 0]} scale={[8.35, 123.67, 2.04]}>
          <mesh geometry={nodes.Cube026_Wood006_0.geometry} material={materials['Wood.006']} />
          <mesh geometry={nodes.Cube026_Material003_0.geometry} material={materials['Material.003']} />
        </group>
        <mesh geometry={nodes.Cube002_Signal_0.geometry} material={materials.Signal} position={[1007.28, 372.95, -2049.5]} rotation={[-Math.PI / 2, 0, 0]} scale={[5.13, 44.19, 1.51]} />
        <mesh geometry={nodes.Cube003_Signal002_0.geometry} material={materials['Signal.002']} position={[1695.15, 463.63, -2049.5]} rotation={[-Math.PI / 2, 0, 0]} scale={[5.13, 44.19, 1.51]} />
        <mesh geometry={nodes.Cube020_Signal003_0.geometry} material={materials['Signal.003']} position={[1007.5, 463.63, 2700.48]} rotation={[-Math.PI / 2, 0, -1.57]} scale={[5.13, 44.19, 1.51]} />
        <mesh geometry={nodes.Cube021_Signal004_0.geometry} material={materials['Signal.004']} position={[1009.79, 372.95, 2012.6]} rotation={[-Math.PI / 2, 0, -1.57]} scale={[5.13, 44.19, 1.51]} />
      </group>
    </group>
  )
}

useGLTF.preload('/18th_century_city_building_low_poly.glb')
