/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\18th_century_city_building_low_poly.glb
Author: Zaheer Ul Islam (https://sketchfab.com/ZaheerUlIslam)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/18th-century-city-building-low-poly-3a2bdf0032424f78bbfdcc003624b95d
Title: 18th Century City Building Low Poly
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function AncientBuildModel(props) {
  const { nodes, materials } = useGLTF(
    "/18th_century_city_building_low_poly.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
   
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[336.36, 910.95, 358.38]}
        >
          <mesh
            geometry={nodes.Building_Texture_0.geometry}
            material={materials.Texture}
          />
          <mesh
            geometry={nodes.Building_Base001_0.geometry}
            material={materials["Base.001"]}
          />
          <mesh
            geometry={nodes.Building_Roof_0.geometry}
            material={materials.Roof}
          />
          <mesh
            geometry={nodes.Building_ButimenRoofing_0.geometry}
            material={materials.ButimenRoofing}
          />
        </group>
        
        <group position={[916.72, 83.37, 701.98]} rotation={[-Math.PI / 2, 1.55, 0]} scale={[8.35, 123.67, 2.04]}>
          <mesh geometry={nodes.Cube026_Wood006_0.geometry} material={materials['Wood.006']} />
          <mesh geometry={nodes.Cube026_Material003_0.geometry} material={materials['Material.003']} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/18th_century_city_building_low_poly.glb");
