/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tower_house_design.glb
Author: 3DHaupt (https://sketchfab.com/dennish2010)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/tower-house-design-a972a15421a942429f1279824e00c042
Title: Tower House Design
*/


import React, { useRef ,useState} from 'react'
import { useGLTF } from '@react-three/drei'
import { Tooltip } from 'react-tooltip'
import { Html } from '@react-three/drei'
export function TowerModel(props) {
  const group = useRef()

  // Hold state for hovered and clicked events
  const [hovered, hover] = useState(false);
  const [clicked, click] = useState(false);
  const { nodes, materials} = useGLTF('/virtualCity/tower_house_design.glb')
  return (
    <>

<Html>

<Tooltip anchorSelect=".my-anchor-element" />
</Html>
<group ref={group} {...props}  

scale={clicked ? 1.5 : 1}
onClick={(event) => click(!clicked)}
onPointerOver={(event) => console.log("hello")}
onPointerOut={(event) => hover(false)} dispose={null}>

<mesh color={hovered ? "hotpink" : "orange"}/>

  <group name="Sketchfab_Scene">
    <group name="Sketchfab_model" rotation={[-Math.PI / 2,0, -10]} scale={0.35}>
      <group name="Root">
        <group name="Cube034" position={[0.8, 0, 0]}>
          <mesh name="Cube034_0" geometry={nodes.Cube034_0.geometry} material={materials.Floor_2} />
        </group>
        <group name="Cube000" position={[0.8, 0, 0]}>
          <mesh name="Cube000_0" geometry={nodes.Cube000_0.geometry} material={materials.Gals} />
        </group>
        <group name="Cube022" position={[0.8, 0, 0]}>
          <mesh name="Cube022_0" geometry={nodes.Cube022_0.geometry} material={materials.Gals} />
        </group>
        <group name="Cube035" position={[0.8, 0, 0]}>
          <mesh name="Cube035_0" geometry={nodes.Cube035_0.geometry} material={materials['Material.037']} />
        </group>
        <group name="Cube036" position={[0.8, 0, 0]}>
          <mesh name="Cube036_0" geometry={nodes.Cube036_0.geometry} material={materials['Material.038']} />
        </group>
        <group name="Empty005" position={[1.49, -3.05, 3.16]} scale={[0.38, 1.13, 1.13]}>
          <group name="gartentor_part111" position={[0, -0.02, 2.52]} rotation={[0.05, 0, 0]}>
            <mesh name="gartentor_part111_0" geometry={nodes.gartentor_part111_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part110" position={[0, -0.02, 2.36]}>
            <mesh name="gartentor_part110_0" geometry={nodes.gartentor_part110_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part109" position={[0, -0.02, 2.21]}>
            <mesh name="gartentor_part109_0" geometry={nodes.gartentor_part109_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part108" position={[0, -0.02, 2.05]}>
            <mesh name="gartentor_part108_0" geometry={nodes.gartentor_part108_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part107" position={[0, -0.02, 1.89]}>
            <mesh name="gartentor_part107_0" geometry={nodes.gartentor_part107_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part106" position={[0, -0.02, 1.74]}>
            <mesh name="gartentor_part106_0" geometry={nodes.gartentor_part106_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part105" position={[0, -0.02, 1.58]}>
            <mesh name="gartentor_part105_0" geometry={nodes.gartentor_part105_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part104" position={[0, -0.02, 1.42]}>
            <mesh name="gartentor_part104_0" geometry={nodes.gartentor_part104_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part103" position={[0, -0.02, 1.26]}>
            <mesh name="gartentor_part103_0" geometry={nodes.gartentor_part103_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part102" position={[0, -0.02, 1.11]}>
            <mesh name="gartentor_part102_0" geometry={nodes.gartentor_part102_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part101" position={[0, -0.02, 0.95]}>
            <mesh name="gartentor_part101_0" geometry={nodes.gartentor_part101_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part100" position={[0, -0.02, 0.79]}>
            <mesh name="gartentor_part100_0" geometry={nodes.gartentor_part100_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part099" position={[0, -0.02, 0.63]}>
            <mesh name="gartentor_part099_0" geometry={nodes.gartentor_part099_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part098" position={[0, -0.02, 0.48]}>
            <mesh name="gartentor_part098_0" geometry={nodes.gartentor_part098_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part097" position={[0, -0.02, 0.32]}>
            <mesh name="gartentor_part097_0" geometry={nodes.gartentor_part097_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part096" position={[0, -0.02, 0.16]}>
            <mesh name="gartentor_part096_0" geometry={nodes.gartentor_part096_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="Cube006">
            <mesh name="Cube006_0" geometry={nodes.Cube006_0.geometry} material={materials.building_02_Door} />
          </group>
        </group>
        <group name="Plane" position={[-1, 0, 0]}>
          <mesh name="Plane_0" geometry={nodes.Plane_0.geometry} material={materials['Material.002']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.001']} />
        </group>
        <group name="Empty001" position={[-1.36, -3.05, 3.16]} scale={[0.38, 1.13, 1.13]}>
          <group name="gartentor_part047" position={[0, -0.02, 2.52]} rotation={[0.05, 0, 0]}>
            <mesh name="gartentor_part047_0" geometry={nodes.gartentor_part047_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part046" position={[0, -0.02, 2.36]}>
            <mesh name="gartentor_part046_0" geometry={nodes.gartentor_part046_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part045" position={[0, -0.02, 2.21]}>
            <mesh name="gartentor_part045_0" geometry={nodes.gartentor_part045_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part044" position={[0, -0.02, 2.05]}>
            <mesh name="gartentor_part044_0" geometry={nodes.gartentor_part044_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part043" position={[0, -0.02, 1.89]}>
            <mesh name="gartentor_part043_0" geometry={nodes.gartentor_part043_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part042" position={[0, -0.02, 1.74]}>
            <mesh name="gartentor_part042_0" geometry={nodes.gartentor_part042_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part041" position={[0, -0.02, 1.58]}>
            <mesh name="gartentor_part041_0" geometry={nodes.gartentor_part041_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part040" position={[0, -0.02, 1.42]}>
            <mesh name="gartentor_part040_0" geometry={nodes.gartentor_part040_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part039" position={[0, -0.02, 1.26]}>
            <mesh name="gartentor_part039_0" geometry={nodes.gartentor_part039_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part038" position={[0, -0.02, 1.11]}>
            <mesh name="gartentor_part038_0" geometry={nodes.gartentor_part038_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part037" position={[0, -0.02, 0.95]}>
            <mesh name="gartentor_part037_0" geometry={nodes.gartentor_part037_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part036" position={[0, -0.02, 0.79]}>
            <mesh name="gartentor_part036_0" geometry={nodes.gartentor_part036_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part035" position={[0, -0.02, 0.63]}>
            <mesh name="gartentor_part035_0" geometry={nodes.gartentor_part035_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part034" position={[0, -0.02, 0.48]}>
            <mesh name="gartentor_part034_0" geometry={nodes.gartentor_part034_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part033" position={[0, -0.02, 0.32]}>
            <mesh name="gartentor_part033_0" geometry={nodes.gartentor_part033_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part032" position={[0, -0.02, 0.16]}>
            <mesh name="gartentor_part032_0" geometry={nodes.gartentor_part032_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="Cube004">
            <mesh name="Cube004_0" geometry={nodes.Cube004_0.geometry} material={materials.building_02_Door} />
          </group>
        </group>
        <group name="Empty000" position={[0.08, -2.97, 6.17]} scale={[1.11, 0.73, 0.73]}>
          <group name="gartentor_part015" position={[0, -0.02, 0.16]}>
            <mesh name="gartentor_part015_0" geometry={nodes.gartentor_part015_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part014" position={[0, -0.02, 0.32]}>
            <mesh name="gartentor_part014_0" geometry={nodes.gartentor_part014_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part013" position={[0, -0.02, 0.48]}>
            <mesh name="gartentor_part013_0" geometry={nodes.gartentor_part013_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part012" position={[0, -0.02, 0.63]}>
            <mesh name="gartentor_part012_0" geometry={nodes.gartentor_part012_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part011" position={[0, -0.02, 0.79]}>
            <mesh name="gartentor_part011_0" geometry={nodes.gartentor_part011_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part010" position={[0, -0.02, 0.95]}>
            <mesh name="gartentor_part010_0" geometry={nodes.gartentor_part010_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part009" position={[0, -0.02, 1.11]}>
            <mesh name="gartentor_part009_0" geometry={nodes.gartentor_part009_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part008" position={[0, -0.02, 1.26]}>
            <mesh name="gartentor_part008_0" geometry={nodes.gartentor_part008_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part007" position={[0, -0.02, 1.42]}>
            <mesh name="gartentor_part007_0" geometry={nodes.gartentor_part007_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part006" position={[0, -0.02, 1.58]}>
            <mesh name="gartentor_part006_0" geometry={nodes.gartentor_part006_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part005" position={[0, -0.02, 1.74]}>
            <mesh name="gartentor_part005_0" geometry={nodes.gartentor_part005_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part004" position={[0, -0.02, 1.89]}>
            <mesh name="gartentor_part004_0" geometry={nodes.gartentor_part004_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part003" position={[0, -0.02, 2.05]}>
            <mesh name="gartentor_part003_0" geometry={nodes.gartentor_part003_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part002" position={[0, -0.02, 2.21]}>
            <mesh name="gartentor_part002_0" geometry={nodes.gartentor_part002_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part001" position={[0, -0.02, 2.36]}>
            <mesh name="gartentor_part001_0" geometry={nodes.gartentor_part001_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part000" position={[0, -0.02, 2.52]} rotation={[0.05, 0, 0]}>
            <mesh name="gartentor_part000_0" geometry={nodes.gartentor_part000_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="Cube002">
            <mesh name="Cube002_0" geometry={nodes.Cube002_0.geometry} material={materials.building_02_Door} />
          </group>
        </group>
        <group name="Empty002" position={[0.07, -3.05, 3.16]} scale={[0.38, 1.13, 1.13]}>
          <group name="gartentor_part287" position={[0, -0.02, 2.52]} rotation={[0.05, 0, 0]}>
            <mesh name="gartentor_part287_0" geometry={nodes.gartentor_part287_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part286" position={[0, -0.02, 2.36]}>
            <mesh name="gartentor_part286_0" geometry={nodes.gartentor_part286_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part285" position={[0, -0.02, 2.21]}>
            <mesh name="gartentor_part285_0" geometry={nodes.gartentor_part285_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part284" position={[0, -0.02, 2.05]}>
            <mesh name="gartentor_part284_0" geometry={nodes.gartentor_part284_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part283" position={[0, -0.02, 1.89]}>
            <mesh name="gartentor_part283_0" geometry={nodes.gartentor_part283_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part282" position={[0, -0.02, 1.74]}>
            <mesh name="gartentor_part282_0" geometry={nodes.gartentor_part282_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part281" position={[0, -0.02, 1.58]}>
            <mesh name="gartentor_part281_0" geometry={nodes.gartentor_part281_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part280" position={[0, -0.02, 1.42]}>
            <mesh name="gartentor_part280_0" geometry={nodes.gartentor_part280_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part279" position={[0, -0.02, 1.26]}>
            <mesh name="gartentor_part279_0" geometry={nodes.gartentor_part279_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part278" position={[0, -0.02, 1.11]}>
            <mesh name="gartentor_part278_0" geometry={nodes.gartentor_part278_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part277" position={[0, -0.02, 0.95]}>
            <mesh name="gartentor_part277_0" geometry={nodes.gartentor_part277_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part276" position={[0, -0.02, 0.79]}>
            <mesh name="gartentor_part276_0" geometry={nodes.gartentor_part276_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part275" position={[0, -0.02, 0.63]}>
            <mesh name="gartentor_part275_0" geometry={nodes.gartentor_part275_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part274" position={[0, -0.02, 0.48]}>
            <mesh name="gartentor_part274_0" geometry={nodes.gartentor_part274_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part273" position={[0, -0.02, 0.32]}>
            <mesh name="gartentor_part273_0" geometry={nodes.gartentor_part273_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part272" position={[0, -0.02, 0.16]}>
            <mesh name="gartentor_part272_0" geometry={nodes.gartentor_part272_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="Cube005">
            <mesh name="Cube005_0" geometry={nodes.Cube005_0.geometry} material={materials.building_02_Door} />
          </group>
        </group>
        <group name="Empty003" position={[0.08, 2.9, 6.17]} rotation={[0, 0, -Math.PI]} scale={[1.11, 0.73, 0.73]}>
          <group name="gartentor_part303" position={[0, -0.02, 2.52]} rotation={[0.05, 0, 0]}>
            <mesh name="gartentor_part303_0" geometry={nodes.gartentor_part303_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part302" position={[0, -0.02, 2.36]}>
            <mesh name="gartentor_part302_0" geometry={nodes.gartentor_part302_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part301" position={[0, -0.02, 2.21]}>
            <mesh name="gartentor_part301_0" geometry={nodes.gartentor_part301_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part300" position={[0, -0.02, 2.05]}>
            <mesh name="gartentor_part300_0" geometry={nodes.gartentor_part300_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part299" position={[0, -0.02, 1.89]}>
            <mesh name="gartentor_part299_0" geometry={nodes.gartentor_part299_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part298" position={[0, -0.02, 1.74]}>
            <mesh name="gartentor_part298_0" geometry={nodes.gartentor_part298_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part297" position={[0, -0.02, 1.58]}>
            <mesh name="gartentor_part297_0" geometry={nodes.gartentor_part297_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part296" position={[0, -0.02, 1.42]}>
            <mesh name="gartentor_part296_0" geometry={nodes.gartentor_part296_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part295" position={[0, -0.02, 1.26]}>
            <mesh name="gartentor_part295_0" geometry={nodes.gartentor_part295_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part294" position={[0, -0.02, 1.11]}>
            <mesh name="gartentor_part294_0" geometry={nodes.gartentor_part294_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part293" position={[0, -0.02, 0.95]}>
            <mesh name="gartentor_part293_0" geometry={nodes.gartentor_part293_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part292" position={[0, -0.02, 0.79]}>
            <mesh name="gartentor_part292_0" geometry={nodes.gartentor_part292_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part291" position={[0, -0.02, 0.63]}>
            <mesh name="gartentor_part291_0" geometry={nodes.gartentor_part291_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part290" position={[0, -0.02, 0.48]}>
            <mesh name="gartentor_part290_0" geometry={nodes.gartentor_part290_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part289" position={[0, -0.02, 0.32]}>
            <mesh name="gartentor_part289_0" geometry={nodes.gartentor_part289_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part288" position={[0, -0.02, 0.16]}>
            <mesh name="gartentor_part288_0" geometry={nodes.gartentor_part288_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="Cube013">
            <mesh name="Cube013_0" geometry={nodes.Cube013_0.geometry} material={materials.building_02_Door} />
          </group>
        </group>
        <group name="Empty004" position={[0.83, -3.01, 8.16]} scale={[1.53, 0.31, 0.31]}>
          <group name="gartentor_part319" position={[0, -0.02, 2.52]} rotation={[0.05, 0, 0]}>
            <mesh name="gartentor_part319_0" geometry={nodes.gartentor_part319_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part318" position={[0, -0.02, 2.36]}>
            <mesh name="gartentor_part318_0" geometry={nodes.gartentor_part318_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part317" position={[0, -0.02, 2.21]}>
            <mesh name="gartentor_part317_0" geometry={nodes.gartentor_part317_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part316" position={[0, -0.02, 2.05]}>
            <mesh name="gartentor_part316_0" geometry={nodes.gartentor_part316_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part315" position={[0, -0.02, 1.89]}>
            <mesh name="gartentor_part315_0" geometry={nodes.gartentor_part315_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part314" position={[0, -0.02, 1.74]}>
            <mesh name="gartentor_part314_0" geometry={nodes.gartentor_part314_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part313" position={[0, -0.02, 1.58]}>
            <mesh name="gartentor_part313_0" geometry={nodes.gartentor_part313_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part312" position={[0, -0.02, 1.42]}>
            <mesh name="gartentor_part312_0" geometry={nodes.gartentor_part312_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part311" position={[0, -0.02, 1.26]}>
            <mesh name="gartentor_part311_0" geometry={nodes.gartentor_part311_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part310" position={[0, -0.02, 1.11]}>
            <mesh name="gartentor_part310_0" geometry={nodes.gartentor_part310_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part309" position={[0, -0.02, 0.95]}>
            <mesh name="gartentor_part309_0" geometry={nodes.gartentor_part309_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part308" position={[0, -0.02, 0.79]}>
            <mesh name="gartentor_part308_0" geometry={nodes.gartentor_part308_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part307" position={[0, -0.02, 0.63]}>
            <mesh name="gartentor_part307_0" geometry={nodes.gartentor_part307_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part306" position={[0, -0.02, 0.48]}>
            <mesh name="gartentor_part306_0" geometry={nodes.gartentor_part306_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part305" position={[0, -0.02, 0.32]}>
            <mesh name="gartentor_part305_0" geometry={nodes.gartentor_part305_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part304" position={[0, -0.02, 0.16]}>
            <mesh name="gartentor_part304_0" geometry={nodes.gartentor_part304_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="Cube010">
            <mesh name="Cube010_0" geometry={nodes.Cube010_0.geometry} material={materials.building_02_Door} />
          </group>
        </group>
        <group name="Empty009" position={[0.83, 2.92, 8.16]} rotation={[0, 0, -Math.PI]} scale={[1.53, 0.31, 0.31]}>
          <group name="gartentor_part335" position={[0, -0.02, 2.52]} rotation={[0.05, 0, 0]}>
            <mesh name="gartentor_part335_0" geometry={nodes.gartentor_part335_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part334" position={[0, -0.02, 2.36]}>
            <mesh name="gartentor_part334_0" geometry={nodes.gartentor_part334_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part333" position={[0, -0.02, 2.21]}>
            <mesh name="gartentor_part333_0" geometry={nodes.gartentor_part333_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part332" position={[0, -0.02, 2.05]}>
            <mesh name="gartentor_part332_0" geometry={nodes.gartentor_part332_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part331" position={[0, -0.02, 1.89]}>
            <mesh name="gartentor_part331_0" geometry={nodes.gartentor_part331_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part330" position={[0, -0.02, 1.74]}>
            <mesh name="gartentor_part330_0" geometry={nodes.gartentor_part330_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part329" position={[0, -0.02, 1.58]}>
            <mesh name="gartentor_part329_0" geometry={nodes.gartentor_part329_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part328" position={[0, -0.02, 1.42]}>
            <mesh name="gartentor_part328_0" geometry={nodes.gartentor_part328_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part327" position={[0, -0.02, 1.26]}>
            <mesh name="gartentor_part327_0" geometry={nodes.gartentor_part327_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part326" position={[0, -0.02, 1.11]}>
            <mesh name="gartentor_part326_0" geometry={nodes.gartentor_part326_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part325" position={[0, -0.02, 0.95]}>
            <mesh name="gartentor_part325_0" geometry={nodes.gartentor_part325_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part324" position={[0, -0.02, 0.79]}>
            <mesh name="gartentor_part324_0" geometry={nodes.gartentor_part324_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part323" position={[0, -0.02, 0.63]}>
            <mesh name="gartentor_part323_0" geometry={nodes.gartentor_part323_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part322" position={[0, -0.02, 0.48]}>
            <mesh name="gartentor_part322_0" geometry={nodes.gartentor_part322_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part321" position={[0, -0.02, 0.32]}>
            <mesh name="gartentor_part321_0" geometry={nodes.gartentor_part321_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part320" position={[0, -0.02, 0.16]}>
            <mesh name="gartentor_part320_0" geometry={nodes.gartentor_part320_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="Cube017">
            <mesh name="Cube017_0" geometry={nodes.Cube017_0.geometry} material={materials.building_02_Door} />
          </group>
        </group>
        <group name="Empty012" position={[0.73, -0.1, 12.04]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[1.86, 1.59, 1.59]}>
          <group name="gartentor_part351" position={[0, -0.02, 2.52]} rotation={[0.05, 0, 0]}>
            <mesh name="gartentor_part351_0" geometry={nodes.gartentor_part351_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part350" position={[0, -0.02, 2.36]}>
            <mesh name="gartentor_part350_0" geometry={nodes.gartentor_part350_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part349" position={[0, -0.02, 2.21]}>
            <mesh name="gartentor_part349_0" geometry={nodes.gartentor_part349_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part348" position={[0, -0.02, 2.05]}>
            <mesh name="gartentor_part348_0" geometry={nodes.gartentor_part348_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part347" position={[0, -0.02, 1.89]}>
            <mesh name="gartentor_part347_0" geometry={nodes.gartentor_part347_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part346" position={[0, -0.02, 1.74]}>
            <mesh name="gartentor_part346_0" geometry={nodes.gartentor_part346_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part345" position={[0, -0.02, 1.58]}>
            <mesh name="gartentor_part345_0" geometry={nodes.gartentor_part345_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part344" position={[0, -0.02, 1.42]}>
            <mesh name="gartentor_part344_0" geometry={nodes.gartentor_part344_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part343" position={[0, -0.02, 1.26]}>
            <mesh name="gartentor_part343_0" geometry={nodes.gartentor_part343_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part342" position={[0, -0.02, 1.11]}>
            <mesh name="gartentor_part342_0" geometry={nodes.gartentor_part342_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part341" position={[0, -0.02, 0.95]}>
            <mesh name="gartentor_part341_0" geometry={nodes.gartentor_part341_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part340" position={[0, -0.02, 0.79]}>
            <mesh name="gartentor_part340_0" geometry={nodes.gartentor_part340_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part339" position={[0, -0.02, 0.63]}>
            <mesh name="gartentor_part339_0" geometry={nodes.gartentor_part339_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part338" position={[0, -0.02, 0.48]}>
            <mesh name="gartentor_part338_0" geometry={nodes.gartentor_part338_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part337" position={[0, -0.02, 0.32]}>
            <mesh name="gartentor_part337_0" geometry={nodes.gartentor_part337_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part336" position={[0, -0.02, 0.16]}>
            <mesh name="gartentor_part336_0" geometry={nodes.gartentor_part336_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="Cube011">
            <mesh name="Cube011_0" geometry={nodes.Cube011_0.geometry} material={materials.building_02_Door} />
          </group>
        </group>
        <group name="Empty015" position={[0.73, -0.1, 12.04]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[1.86, 1.59, 1.59]}>
          <group name="gartentor_part367" position={[0, -0.02, 2.52]} rotation={[0.05, 0, 0]}>
            <mesh name="gartentor_part367_0" geometry={nodes.gartentor_part367_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part366" position={[0, -0.02, 2.36]}>
            <mesh name="gartentor_part366_0" geometry={nodes.gartentor_part366_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part365" position={[0, -0.02, 2.21]}>
            <mesh name="gartentor_part365_0" geometry={nodes.gartentor_part365_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part364" position={[0, -0.02, 2.05]}>
            <mesh name="gartentor_part364_0" geometry={nodes.gartentor_part364_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part363" position={[0, -0.02, 1.89]}>
            <mesh name="gartentor_part363_0" geometry={nodes.gartentor_part363_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part362" position={[0, -0.02, 1.74]}>
            <mesh name="gartentor_part362_0" geometry={nodes.gartentor_part362_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part361" position={[0, -0.02, 1.58]}>
            <mesh name="gartentor_part361_0" geometry={nodes.gartentor_part361_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part360" position={[0, -0.02, 1.42]}>
            <mesh name="gartentor_part360_0" geometry={nodes.gartentor_part360_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part359" position={[0, -0.02, 1.26]}>
            <mesh name="gartentor_part359_0" geometry={nodes.gartentor_part359_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part358" position={[0, -0.02, 1.11]}>
            <mesh name="gartentor_part358_0" geometry={nodes.gartentor_part358_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part357" position={[0, -0.02, 0.95]}>
            <mesh name="gartentor_part357_0" geometry={nodes.gartentor_part357_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part356" position={[0, -0.02, 0.79]}>
            <mesh name="gartentor_part356_0" geometry={nodes.gartentor_part356_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part355" position={[0, -0.02, 0.63]}>
            <mesh name="gartentor_part355_0" geometry={nodes.gartentor_part355_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part354" position={[0, -0.02, 0.48]}>
            <mesh name="gartentor_part354_0" geometry={nodes.gartentor_part354_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part353" position={[0, -0.02, 0.32]}>
            <mesh name="gartentor_part353_0" geometry={nodes.gartentor_part353_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part352" position={[0, -0.02, 0.16]}>
            <mesh name="gartentor_part352_0" geometry={nodes.gartentor_part352_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="Cube014">
            <mesh name="Cube014_0" geometry={nodes.Cube014_0.geometry} material={materials.building_02_Door} />
          </group>
        </group>
        <group name="Empty016" position={[0.3, 2.76, 0.12]}>
          <group name="gartentor_part383" position={[0, -0.02, 2.52]} rotation={[0.05, 0, 0]}>
            <mesh name="gartentor_part383_0" geometry={nodes.gartentor_part383_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part382" position={[0, -0.02, 2.36]}>
            <mesh name="gartentor_part382_0" geometry={nodes.gartentor_part382_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part381" position={[0, -0.02, 2.21]}>
            <mesh name="gartentor_part381_0" geometry={nodes.gartentor_part381_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part380" position={[0, -0.02, 2.05]}>
            <mesh name="gartentor_part380_0" geometry={nodes.gartentor_part380_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part379" position={[0, -0.02, 1.89]}>
            <mesh name="gartentor_part379_0" geometry={nodes.gartentor_part379_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part378" position={[0, -0.02, 1.74]}>
            <mesh name="gartentor_part378_0" geometry={nodes.gartentor_part378_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part377" position={[0, -0.02, 1.58]}>
            <mesh name="gartentor_part377_0" geometry={nodes.gartentor_part377_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part376" position={[0, -0.02, 1.42]}>
            <mesh name="gartentor_part376_0" geometry={nodes.gartentor_part376_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part375" position={[0, -0.02, 1.26]}>
            <mesh name="gartentor_part375_0" geometry={nodes.gartentor_part375_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part374" position={[0, -0.02, 1.11]}>
            <mesh name="gartentor_part374_0" geometry={nodes.gartentor_part374_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part373" position={[0, -0.02, 0.95]}>
            <mesh name="gartentor_part373_0" geometry={nodes.gartentor_part373_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part372" position={[0, -0.02, 0.79]}>
            <mesh name="gartentor_part372_0" geometry={nodes.gartentor_part372_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part371" position={[0, -0.02, 0.63]}>
            <mesh name="gartentor_part371_0" geometry={nodes.gartentor_part371_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part370" position={[0, -0.02, 0.48]}>
            <mesh name="gartentor_part370_0" geometry={nodes.gartentor_part370_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part369" position={[0, -0.02, 0.32]}>
            <mesh name="gartentor_part369_0" geometry={nodes.gartentor_part369_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part368" position={[0, -0.02, 0.16]}>
            <mesh name="gartentor_part368_0" geometry={nodes.gartentor_part368_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="Cube016">
            <mesh name="Cube016_0" geometry={nodes.Cube016_0.geometry} material={materials.building_02_Door} />
          </group>
        </group>
        <group name="Empty008" position={[0.09, 3.98, 3.1]} scale={[1.13, 1.09, 1.09]}>
          <group name="gartentor_part031" position={[0, -0.02, 2.52]} rotation={[0.05, 0, 0]}>
            <mesh name="gartentor_part031_0" geometry={nodes.gartentor_part031_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part030" position={[0, -0.02, 2.36]}>
            <mesh name="gartentor_part030_0" geometry={nodes.gartentor_part030_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part029" position={[0, -0.02, 2.21]}>
            <mesh name="gartentor_part029_0" geometry={nodes.gartentor_part029_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part028" position={[0, -0.02, 2.05]}>
            <mesh name="gartentor_part028_0" geometry={nodes.gartentor_part028_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part027" position={[0, -0.02, 1.89]}>
            <mesh name="gartentor_part027_0" geometry={nodes.gartentor_part027_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part026" position={[0, -0.02, 1.74]}>
            <mesh name="gartentor_part026_0" geometry={nodes.gartentor_part026_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part025" position={[0, -0.02, 1.58]}>
            <mesh name="gartentor_part025_0" geometry={nodes.gartentor_part025_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part024" position={[0, -0.02, 1.42]}>
            <mesh name="gartentor_part024_0" geometry={nodes.gartentor_part024_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part023" position={[0, -0.02, 1.26]}>
            <mesh name="gartentor_part023_0" geometry={nodes.gartentor_part023_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part022" position={[0, -0.02, 1.11]}>
            <mesh name="gartentor_part022_0" geometry={nodes.gartentor_part022_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part021" position={[0, -0.02, 0.95]}>
            <mesh name="gartentor_part021_0" geometry={nodes.gartentor_part021_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part020" position={[0, -0.02, 0.79]}>
            <mesh name="gartentor_part020_0" geometry={nodes.gartentor_part020_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part019" position={[0, -0.02, 0.63]}>
            <mesh name="gartentor_part019_0" geometry={nodes.gartentor_part019_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part018" position={[0, -0.02, 0.48]}>
            <mesh name="gartentor_part018_0" geometry={nodes.gartentor_part018_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part017" position={[0, -0.02, 0.32]}>
            <mesh name="gartentor_part017_0" geometry={nodes.gartentor_part017_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part016" position={[0, -0.02, 0.16]}>
            <mesh name="gartentor_part016_0" geometry={nodes.gartentor_part016_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="Cube001">
            <mesh name="Cube001_0" geometry={nodes.Cube001_0.geometry} material={materials.building_02_Door} />
          </group>
        </group>
        <group name="Empty011" position={[3.16, 2.92, 5.14]} rotation={[0, 0, -Math.PI]} scale={0.29}>
          <group name="gartentor_part399" position={[0, -0.02, 2.52]} rotation={[0.05, 0, 0]}>
            <mesh name="gartentor_part399_0" geometry={nodes.gartentor_part399_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part398" position={[0, -0.02, 2.36]}>
            <mesh name="gartentor_part398_0" geometry={nodes.gartentor_part398_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part397" position={[0, -0.02, 2.21]}>
            <mesh name="gartentor_part397_0" geometry={nodes.gartentor_part397_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part396" position={[0, -0.02, 2.05]}>
            <mesh name="gartentor_part396_0" geometry={nodes.gartentor_part396_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part395" position={[0, -0.02, 1.89]}>
            <mesh name="gartentor_part395_0" geometry={nodes.gartentor_part395_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part394" position={[0, -0.02, 1.74]}>
            <mesh name="gartentor_part394_0" geometry={nodes.gartentor_part394_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part393" position={[0, -0.02, 1.58]}>
            <mesh name="gartentor_part393_0" geometry={nodes.gartentor_part393_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part392" position={[0, -0.02, 1.42]}>
            <mesh name="gartentor_part392_0" geometry={nodes.gartentor_part392_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part391" position={[0, -0.02, 1.26]}>
            <mesh name="gartentor_part391_0" geometry={nodes.gartentor_part391_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part390" position={[0, -0.02, 1.11]}>
            <mesh name="gartentor_part390_0" geometry={nodes.gartentor_part390_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part389" position={[0, -0.02, 0.95]}>
            <mesh name="gartentor_part389_0" geometry={nodes.gartentor_part389_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part388" position={[0, -0.02, 0.79]}>
            <mesh name="gartentor_part388_0" geometry={nodes.gartentor_part388_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part387" position={[0, -0.02, 0.63]}>
            <mesh name="gartentor_part387_0" geometry={nodes.gartentor_part387_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part386" position={[0, -0.02, 0.48]}>
            <mesh name="gartentor_part386_0" geometry={nodes.gartentor_part386_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part385" position={[0, -0.02, 0.32]}>
            <mesh name="gartentor_part385_0" geometry={nodes.gartentor_part385_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part384" position={[0, -0.02, 0.16]}>
            <mesh name="gartentor_part384_0" geometry={nodes.gartentor_part384_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="Cube009">
            <mesh name="Cube009_0" geometry={nodes.Cube009_0.geometry} material={materials.building_02_Door} />
          </group>
        </group>
        <group name="Empty006" position={[3.74, 1.21, 5.16]} rotation={[0, 0, -Math.PI / 2]} scale={[0.86, 0.29, 0.29]}>
          <group name="gartentor_part415" position={[0, -0.02, 2.52]} rotation={[0.05, 0, 0]}>
            <mesh name="gartentor_part415_0" geometry={nodes.gartentor_part415_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part414" position={[0, -0.02, 2.36]}>
            <mesh name="gartentor_part414_0" geometry={nodes.gartentor_part414_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part413" position={[0, -0.02, 2.21]}>
            <mesh name="gartentor_part413_0" geometry={nodes.gartentor_part413_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part412" position={[0, -0.02, 2.05]}>
            <mesh name="gartentor_part412_0" geometry={nodes.gartentor_part412_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part411" position={[0, -0.02, 1.89]}>
            <mesh name="gartentor_part411_0" geometry={nodes.gartentor_part411_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part410" position={[0, -0.02, 1.74]}>
            <mesh name="gartentor_part410_0" geometry={nodes.gartentor_part410_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part409" position={[0, -0.02, 1.58]}>
            <mesh name="gartentor_part409_0" geometry={nodes.gartentor_part409_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part408" position={[0, -0.02, 1.42]}>
            <mesh name="gartentor_part408_0" geometry={nodes.gartentor_part408_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part407" position={[0, -0.02, 1.26]}>
            <mesh name="gartentor_part407_0" geometry={nodes.gartentor_part407_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part406" position={[0, -0.02, 1.11]}>
            <mesh name="gartentor_part406_0" geometry={nodes.gartentor_part406_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part405" position={[0, -0.02, 0.95]}>
            <mesh name="gartentor_part405_0" geometry={nodes.gartentor_part405_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part404" position={[0, -0.02, 0.79]}>
            <mesh name="gartentor_part404_0" geometry={nodes.gartentor_part404_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part403" position={[0, -0.02, 0.63]}>
            <mesh name="gartentor_part403_0" geometry={nodes.gartentor_part403_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part402" position={[0, -0.02, 0.48]}>
            <mesh name="gartentor_part402_0" geometry={nodes.gartentor_part402_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part401" position={[0, -0.02, 0.32]}>
            <mesh name="gartentor_part401_0" geometry={nodes.gartentor_part401_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part400" position={[0, -0.02, 0.16]}>
            <mesh name="gartentor_part400_0" geometry={nodes.gartentor_part400_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="Cube007">
            <mesh name="Cube007_0" geometry={nodes.Cube007_0.geometry} material={materials.building_02_Door} />
          </group>
        </group>
        <group name="Empty014" position={[3.74, -1.68, 5.16]} rotation={[0, 0, -Math.PI / 2]} scale={[0.67, 0.29, 0.29]}>
          <group name="gartentor_part431" position={[0, -0.02, 2.52]} rotation={[0.05, 0, 0]}>
            <mesh name="gartentor_part431_0" geometry={nodes.gartentor_part431_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part430" position={[0, -0.02, 2.36]}>
            <mesh name="gartentor_part430_0" geometry={nodes.gartentor_part430_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part429" position={[0, -0.02, 2.21]}>
            <mesh name="gartentor_part429_0" geometry={nodes.gartentor_part429_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part428" position={[0, -0.02, 2.05]}>
            <mesh name="gartentor_part428_0" geometry={nodes.gartentor_part428_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part427" position={[0, -0.02, 1.89]}>
            <mesh name="gartentor_part427_0" geometry={nodes.gartentor_part427_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part426" position={[0, -0.02, 1.74]}>
            <mesh name="gartentor_part426_0" geometry={nodes.gartentor_part426_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part425" position={[0, -0.02, 1.58]}>
            <mesh name="gartentor_part425_0" geometry={nodes.gartentor_part425_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part424" position={[0, -0.02, 1.42]}>
            <mesh name="gartentor_part424_0" geometry={nodes.gartentor_part424_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part423" position={[0, -0.02, 1.26]}>
            <mesh name="gartentor_part423_0" geometry={nodes.gartentor_part423_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part422" position={[0, -0.02, 1.11]}>
            <mesh name="gartentor_part422_0" geometry={nodes.gartentor_part422_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part421" position={[0, -0.02, 0.95]}>
            <mesh name="gartentor_part421_0" geometry={nodes.gartentor_part421_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part420" position={[0, -0.02, 0.79]}>
            <mesh name="gartentor_part420_0" geometry={nodes.gartentor_part420_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part419" position={[0, -0.02, 0.63]}>
            <mesh name="gartentor_part419_0" geometry={nodes.gartentor_part419_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part418" position={[0, -0.02, 0.48]}>
            <mesh name="gartentor_part418_0" geometry={nodes.gartentor_part418_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part417" position={[0, -0.02, 0.32]}>
            <mesh name="gartentor_part417_0" geometry={nodes.gartentor_part417_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part416" position={[0, -0.02, 0.16]}>
            <mesh name="gartentor_part416_0" geometry={nodes.gartentor_part416_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="Cube012">
            <mesh name="Cube012_0" geometry={nodes.Cube012_0.geometry} material={materials.building_02_Door} />
          </group>
        </group>
        <group name="Empty017" position={[-2.1, -0.04, 5.1]} rotation={[0, 0, -Math.PI / 2]} scale={[1.55, 0.36, 0.36]}>
          <group name="gartentor_part447" position={[0, -0.02, 0.16]}>
            <mesh name="gartentor_part447_0" geometry={nodes.gartentor_part447_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part446" position={[0, -0.02, 0.32]}>
            <mesh name="gartentor_part446_0" geometry={nodes.gartentor_part446_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part445" position={[0, -0.02, 0.48]}>
            <mesh name="gartentor_part445_0" geometry={nodes.gartentor_part445_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part444" position={[0, -0.02, 0.63]}>
            <mesh name="gartentor_part444_0" geometry={nodes.gartentor_part444_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part443" position={[0, -0.02, 0.79]}>
            <mesh name="gartentor_part443_0" geometry={nodes.gartentor_part443_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part442" position={[0, -0.02, 0.95]}>
            <mesh name="gartentor_part442_0" geometry={nodes.gartentor_part442_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part441" position={[0, -0.02, 1.11]}>
            <mesh name="gartentor_part441_0" geometry={nodes.gartentor_part441_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part440" position={[0, -0.02, 1.26]}>
            <mesh name="gartentor_part440_0" geometry={nodes.gartentor_part440_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part439" position={[0, -0.02, 1.42]}>
            <mesh name="gartentor_part439_0" geometry={nodes.gartentor_part439_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part438" position={[0, -0.02, 1.58]}>
            <mesh name="gartentor_part438_0" geometry={nodes.gartentor_part438_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part437" position={[0, -0.02, 1.74]}>
            <mesh name="gartentor_part437_0" geometry={nodes.gartentor_part437_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part436" position={[0, -0.02, 1.89]}>
            <mesh name="gartentor_part436_0" geometry={nodes.gartentor_part436_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part435" position={[0, -0.02, 2.05]}>
            <mesh name="gartentor_part435_0" geometry={nodes.gartentor_part435_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part434" position={[0, -0.02, 2.21]}>
            <mesh name="gartentor_part434_0" geometry={nodes.gartentor_part434_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part433" position={[0, -0.02, 2.36]}>
            <mesh name="gartentor_part433_0" geometry={nodes.gartentor_part433_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="gartentor_part432" position={[0, -0.02, 2.52]} rotation={[0.05, 0, 0]}>
            <mesh name="gartentor_part432_0" geometry={nodes.gartentor_part432_0.geometry} material={materials.building_02_Door} />
          </group>
          <group name="Cube015">
            <mesh name="Cube015_0" geometry={nodes.Cube015_0.geometry} material={materials.building_02_Door} />
          </group>
        </group>
        <group name="Cube" position={[2.31, -0.06, 8.84]}>
          <mesh name="Cube_0" geometry={nodes.Cube_0.geometry} material={materials['Material.003']} />
          <mesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="Cube003" position={[0.61, -0.06, 8.84]}>
          <mesh name="Cube003_0" geometry={nodes.Cube003_0.geometry} material={materials['Material.003']} />
          <mesh name="Cube003_1" geometry={nodes.Cube003_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="Cube008" position={[-1.45, -0.06, 8.84]}>
          <mesh name="Cube008_0" geometry={nodes.Cube008_0.geometry} material={materials['Material.003']} />
          <mesh name="Cube008_1" geometry={nodes.Cube008_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="Cube018" position={[-0.59, 2.57, 5.84]}>
          <mesh name="Cube018_0" geometry={nodes.Cube018_0.geometry} material={materials['Material.003']} />
          <mesh name="Cube018_1" geometry={nodes.Cube018_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="Cube019" position={[2.12, 1.11, 5.85]}>
          <mesh name="Cube019_0" geometry={nodes.Cube019_0.geometry} material={materials['Material.003']} />
          <mesh name="Cube019_1" geometry={nodes.Cube019_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="Cube020" position={[2.12, -1.75, 5.81]}>
          <mesh name="Cube020_0" geometry={nodes.Cube020_0.geometry} material={materials['Material.003']} />
          <mesh name="Cube020_1" geometry={nodes.Cube020_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="Cube021" position={[2.83, -0.46, 2.79]}>
          <mesh name="Cube021_0" geometry={nodes.Cube021_0.geometry} material={materials['Material.003']} />
          <mesh name="Cube021_1" geometry={nodes.Cube021_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="Cube023" position={[-0.41, 0.43, 2.79]}>
          <mesh name="Cube023_0" geometry={nodes.Cube023_0.geometry} material={materials['Material.003']} />
          <mesh name="Cube023_1" geometry={nodes.Cube023_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="Cube024" position={[-0.78, -0.27, 5.81]}>
          <mesh name="Cube024_0" geometry={nodes.Cube024_0.geometry} material={materials['Material.003']} />
          <mesh name="Cube024_1" geometry={nodes.Cube024_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="Cube025" position={[3.89, -3.65, 2.85]}>
          <mesh name="Cube025_0" geometry={nodes.Cube025_0.geometry} material={materials['Material.003']} />
          <mesh name="Cube025_1" geometry={nodes.Cube025_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="Cube026" position={[4.39, -3.65, 5.89]}>
          <mesh name="Cube026_0" geometry={nodes.Cube026_0.geometry} material={materials['Material.003']} />
          <mesh name="Cube026_1" geometry={nodes.Cube026_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="Cube027" position={[4.39, -3.65, 8.95]}>
          <mesh name="Cube027_0" geometry={nodes.Cube027_0.geometry} material={materials['Material.003']} />
          <mesh name="Cube027_1" geometry={nodes.Cube027_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="Cube028" position={[4.51, 3.57, 8.95]}>
          <mesh name="Cube028_0" geometry={nodes.Cube028_0.geometry} material={materials['Material.003']} />
          <mesh name="Cube028_1" geometry={nodes.Cube028_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="Cube029" position={[4.51, 3.57, 5.95]}>
          <mesh name="Cube029_0" geometry={nodes.Cube029_0.geometry} material={materials['Material.003']} />
          <mesh name="Cube029_1" geometry={nodes.Cube029_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="Cube030" position={[-2.76, -3.62, 5.96]}>
          <mesh name="Cube030_0" geometry={nodes.Cube030_0.geometry} material={materials['Material.003']} />
          <mesh name="Cube030_1" geometry={nodes.Cube030_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="Cube031" position={[3.8, 3.57, 2.86]}>
          <mesh name="Cube031_0" geometry={nodes.Cube031_0.geometry} material={materials['Material.003']} />
          <mesh name="Cube031_1" geometry={nodes.Cube031_1.geometry} material={materials['Material.004']} />
        </group>
        <group name="Hemi" position={[-9.02, 10.2, 15.83]} rotation={[-0.42, -0.34, -0.1]}>
          <group name="Hemi_1" />
        </group>
        <group name="Hemi001" position={[-4.94, 10.58, 7.98]} rotation={[0.08, -0.52, 0.03]}>
          <group name="Hemi001_1" />
        </group>
        <group name="Cube032" position={[0.8, 0, 0]}>
          <mesh name="Cube032_0" geometry={nodes.Cube032_0.geometry} material={materials.building_02} />
        </group>
        <group name="Cube033" position={[0.8, 0, 0]}>
          <mesh name="Cube033_0" geometry={nodes.Cube033_0.geometry} material={materials['Material.039']} />
        </group>
        
      </group>
    </group>
  </group>
</group>
    
    </>
   
  )
}  

useGLTF.preload('/virtualCity/tower_house_design.glb')
